### ISSUE TITLE
Error: TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'type'

### ISSUE THREAD

**Issue by Terryhung** [dotX12/pyfa-converter#11]
Using the
```
from pyfa_converter import FormDepends
```
and get the error
```
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'type'
```

python: `3.9`

**Comment by dotX12** [comment]
> Using the
> 
> ```
> from pyfa_converter import FormDepends
> ```
> 
> and get the error
> 
> ```
> TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'type'
> ```
> 
https://github.com/dotX12/pyfa-converter/blob/master/pyfa_converter/depends.py

Need convert typehint A | B to Union[A, B]

**Comment by dotX12** [comment]
if you have time to do it, but i can do it tomorrow.

**Comment by dotX12** [comment]
Fixed in https://github.com/dotX12/pyfa-converter/pull/12
Thx for joining the community!

**Comment by dotX12** [comment]
Release: https://github.com/dotX12/pyfa-converter/releases/tag/1.0.3.0
Pypi: https://pypi.org/project/pyfa-converter/1.0.3.0/
