### ISSUE TITLE
Optional form data

### ISSUE THREAD

**Issue by fgsalomon** [dotX12/pyfa-converter#20]
Hi,

First, thank you for sharing this library, it works great!

I was wondering if there's a way to make the form data optional. I'd like to have an endpoint that would work without body and with a form.

I tried using a union with the model and `None` but it's not working. Example code:

```
from fastapi import FastAPI, Form
from pydantic import BaseModel, validator, ValidationError
from pyfa_converter import FormDepends
from starlette.responses import JSONResponse
from starlette.status import HTTP_422_UNPROCESSABLE_ENTITY

app = FastAPI()


class MyRequest(BaseModel):
    a: str = Form(default=None)
    b: str = Form(default=None)

    @validator('a')
    def a_must_contain_space(cls, v):
        if not v:
            return v
        if ' ' not in v:
            raise ValueError('must contain a space')
        return v.title()


@app.exception_handler(ValidationError)
def exception_handler(_request, exc: ValidationError):
    return JSONResponse(status_code=HTTP_422_UNPROCESSABLE_ENTITY, content={"detail": exc.errors()})


@app.post("/test")
async def test(request: MyRequest | None = FormDepends(MyRequest)):
    if request is None:
        return "Empty form data"
    return "Has form data"
```

`request` is always not `None`, no matter the request. Is there a way to achieve what I intend?

In addition, is there a way to mark the request body in the docs as `multipart/form-data`?:
![image](https://user-images.githubusercontent.com/3149695/220290472-8507f57c-7697-43db-833d-a99ebc4504dc.png)

Thanks.

**Comment by dotX12** [comment]
@fgsalomon, Firstly, Field should be used inside the pydantic model, not Form.
```python3
class MyRequest(BaseModel):
    a: str | None = Field(default=None)
    b: str | None = Field(default=None)

    @validator('a')
    def a_must_contain_space(cls, v):
        if not v:
            return v
        if ' ' not in v:
            raise ValueError('must contain a space')
        return v.title()

```


```python3
@app.post("/test")
async def test(data: MyRequest | None = FormDepends(MyRequest)):
    print(data)
```


![image](https://user-images.githubusercontent.com/64792903/220553246-c971a227-7abf-4738-b144-ea4dac945e4e.png)

**Comment by dotX12** [comment]
Successful sending of the request, if you uncheck the swagger on send empty value buton.

**Comment by fgsalomon** [comment]
> @fgsalomon, Firstly, Field should be used inside the pydantic model, not Form.
> 
> ```python
> class MyRequest(BaseModel):
>     a: str | None = Field(default=None)
>     b: str | None = Field(default=None)

Ooops, my bad. I've fixed this now. However, it seems to me it doesn't change anything.

> Successful sending of the request, if you uncheck the swagger on send empty value buton.

Yeah, I know I can do that but what I would like is the model to be `None` when no data is sent:

```
curl -X 'POST' \
  'http://127.0.0.1:8000/test' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded'
"Has form data"% 
```

**Comment by dotX12** [comment]
@fgsalomon, 
```python3
class MyRequest(BaseModel):
    a: str | None = Field(default=None)
    b: str | None = Field(default=None)

    @root_validator
    def all_is_none(cls, values: dict[str, Any]):
        if all(v is None for v in values.values()):
            raise ValueError("all is none")
        return values
```

**Comment by dotX12** [comment]
You need it?

**Comment by dotX12** [comment]
i don't understand the essence of your task, first you want to allow None value, now you don't want None value...
