### ISSUE TITLE
Default value "False" of BaseModel is ignored

### ISSUE THREAD

**Issue by trashutz** [dotX12/pyfa-converter#22]
The default values of `Field` get ignored.

````python
class TestModel(BaseModel):
    test_field: str | None = Field(default="Some default value", description="Description...")
````

Is the only option to add an validator like this:
````python
    @root_validator
    def set_default_values(cls, values):
        values["test_field"] = (
            "Some default value"
            if values.get("test_field") is None
            else values["test_field"]
        )
        return values
````

Or is there another way for the default values to work?

**Comment by dotX12** [comment]
@trashutz,  hi!
Show how you use it?

I cannot reproduce this issue.
![image](https://user-images.githubusercontent.com/64792903/234129468-ddd2a224-10d2-4b05-9328-b2cb075818c7.png)
![image](https://user-images.githubusercontent.com/64792903/234129518-65f28253-595b-42cd-a799-60fb8d6ebc01.png)

**Comment by trashutz** [comment]
@dotX12 Hi!

Sorry for the delay. I was away and had no time.

I checked my code again and you are right. With string there is no problem. No idea why I didn't catch that. I ran into the problem with a boolean field and wanted to make it clearer with String... After a bit more testing I found only for default value `False` I have a problem. 


````python
from fastapi import FastAPI
from pydantic import BaseModel
from pyfa_converter import FormDepends


class TestPydanticModel(BaseModel):
    default_false: bool = False

class TestPyfaModel(BaseModel):
    default_string: str = "Test"
    default_true: bool = True
    default_false: bool | None = False


app = FastAPI()

@app.post("/test-pyfa")
async def test_pyfa(test_model: TestPyfaModel = FormDepends(TestPyfaModel)):
    return test_model

@app.post("/test-pydantic")
async def test_pydantic(test_model: TestPydanticModel):
    return test_model
````

I took a look at the code and the method `__fill_params` has the line `default=default or None,`. If `default` is `False`, `default or None` will be `None` instead of `False`.

````python
    @classmethod
    def __fill_params(
        cls, param: Callable[..., FieldInfo], model_field: ModelField, default: Any
    ) -> FieldInfo:
        return param(
            default=default or None, # Problem comes from here!
            alias=model_field.field_info.alias or None,
            title=model_field.field_info.title or None,
            description=model_field.field_info.description or None,
            gt=model_field.field_info.gt or None,
            ge=model_field.field_info.ge or None,
            lt=model_field.field_info.lt or None,
            le=model_field.field_info.le or None,
            min_length=model_field.field_info.min_length or None,
            max_length=model_field.field_info.max_length or None,
            regex=model_field.field_info.regex or None,
            **model_field.field_info.extra,
        )
````

**Comment by dotX12** [comment]
Hello, indeed, I think that:

```python3
default_value=default if isinstance(default, bool) else default or None
```

Might fix this issue, I'll run some tests and post it (probably tomorrow)

**Comment by dotX12** [comment]
@trashutz, hello!
Fixed
https://github.com/dotX12/pyfa-converter/releases/tag/1.0.4.1
https://pypi.org/project/pyfa-converter/1.0.4.1/

**Comment by trashutz** [comment]
@dotX12 Hi! 
It works for me.
Thank you!
