### ISSUE TITLE
ImportError: cannot import name 'ModelField' from 'pydantic.fields' 

### ISSUE THREAD

**Issue by damilareisaac** [dotX12/pyfa-converter#28]
`from pyfa_converter.depends import QueryDepends`

Got the error:

```
.../pyfa_converter/main.py",` line 11, in <module>
    from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields'
```
Dependencies List:

- [ ] python3 (3.12.1)
- [ ] pydantic           2.6.4
- [ ] pydantic_core      2.16.3
- [ ] fastapi            0.109.2

I think it is an issues with Pydantic V2 as reported [here](https://stackoverflow.com/questions/77469094/importerror-cannot-import-name-modelfield-from-pydantic-fields)
Downgrading the dependences will not be an option in this case as alot depends on the V2 already

**Comment by dotX12** [comment]
@damilareisaac, see fork: https://github.com/AezaGroup/pyfa-converter-v2 for pydantic v2
