### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by dzcode** [dotX12/pyfa-converter#6]
Hi! The code in this repo seems super useful for us working with pydantic + fastapi, but we can't use it without a `LICENSE`. Could you [add `LICENSE` file to the repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)? MIT is a permissive one if you don't have an opinion otherwise

**Comment by dotX12** [comment]
https://github.com/dotX12/pyfa-converter/releases/tag/1.0.2.0

**Comment by dotX12** [comment]
@dzcode, thanks for joining the community, Made!

**Comment by dzcode** [comment]
thank you!
